# Generated by Django 3.2.16 on 2023-06-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(default=1, max_length=100, verbose_name='Название компании'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='full_address',
            field=models.CharField(default=1, max_length=100, verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('women', 'женщина'), ('men', 'мужчина')], max_length=10, verbose_name='Пол'),
        ),
    ]
