# Generated by Django 3.2.16 on 2023-06-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Последний визит'),
        ),
    ]
